export const listTechno = [
    { name: "Javascript" },
    { name: "Java" },
    { name: "React" },
    { name: "Python" },
    { name: "Mysql" },
    { name: "Postgresql" },
    { name: "Html" },
    { name: "CSS" },
    { name: "C++" },
    { name: "Mongodb" },
    { name: "Express" },
    { name: "Nodejs" },
    { name: "Yarn" },
    { name: "Angular" },
    { name: "PHP" },
    { name: "Rubyonrails" },
    { name: "Flutter" },
  ];